### ISSUE TITLE
add default config generation to application binary

### ISSUE THREAD

**Issue by ATTron** [ATTron/merlin#6]
currently in order to generate a default config you would need to run:  ```make install``` 
 
if you only have the binary (if downloading from the release) you would need to generate a config file by hand

merlin already prompts the user if it cannot locate a config.json file
https://github.com/ATTron/merlin/blob/85a73b96acb048d374c6b6fda7dd163e728a17c3/encoder/config.go#L21-L25
this functionality should be modified to:
- [x] tell the user it cannot locate config.json
- [x] generate default config.json -- can use structs or can grab from repo and place it in location
- [x] tell user a default config.json at specified location and tell them to modify it to their needs
- [x] exit gracefully

**Comment by ektagarg** [comment]
hi @ATTron I would like to take this up.
